
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int PARENTESIS_CIERRE = 13;
  public static final int CHAR = 5;
  public static final int CASE = 35;
  public static final int DIFERENTE = 26;
  public static final int RESTA = 15;
  public static final int INTEGER = 2;
  public static final int DOS_PUNTOS = 39;
  public static final int FOR = 33;
  public static final int IDENTIFICADOR = 42;
  public static final int CORCHETE_CIERRE = 10;
  public static final int IGUALDAD = 25;
  public static final int BOOL = 4;
  public static final int INCREMENTO = 19;
  public static final int SUMA = 14;
  public static final int IF = 30;
  public static final int EOF = 0;
  public static final int RETURN = 38;
  public static final int CORCHETE_APERTURA = 9;
  public static final int DECREMENTO = 20;
  public static final int error = 1;
  public static final int SYNTAX_ERROR = 43;
  public static final int MODULO = 17;
  public static final int NEGACION = 29;
  public static final int APERTURA_DE_BLOQUE = 7;
  public static final int MENOR = 21;
  public static final int BREAK = 37;
  public static final int ASIGNACION = 11;
  public static final int SWITCH = 34;
  public static final int MAYOR = 23;
  public static final int POTENCIA = 18;
  public static final int ELSE = 31;
  public static final int READ = 41;
  public static final int WHILE = 32;
  public static final int DEFAULT = 36;
  public static final int MAYOR_IGUAL = 24;
  public static final int FLOAT = 3;
  public static final int CONJUNCION = 27;
  public static final int STRING = 6;
  public static final int PARENTESIS_APERTURA = 12;
  public static final int DISYUNCION = 28;
  public static final int MENOR_IGUAL = 22;
  public static final int CIERRRE_DE_BLOQUE = 8;
  public static final int PRINT = 40;
  public static final int MULTIPLICACION = 16;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "INTEGER",
  "FLOAT",
  "BOOL",
  "CHAR",
  "STRING",
  "APERTURA_DE_BLOQUE",
  "CIERRRE_DE_BLOQUE",
  "CORCHETE_APERTURA",
  "CORCHETE_CIERRE",
  "ASIGNACION",
  "PARENTESIS_APERTURA",
  "PARENTESIS_CIERRE",
  "SUMA",
  "RESTA",
  "MULTIPLICACION",
  "MODULO",
  "POTENCIA",
  "INCREMENTO",
  "DECREMENTO",
  "MENOR",
  "MENOR_IGUAL",
  "MAYOR",
  "MAYOR_IGUAL",
  "IGUALDAD",
  "DIFERENTE",
  "CONJUNCION",
  "DISYUNCION",
  "NEGACION",
  "IF",
  "ELSE",
  "WHILE",
  "FOR",
  "SWITCH",
  "CASE",
  "DEFAULT",
  "BREAK",
  "RETURN",
  "DOS_PUNTOS",
  "PRINT",
  "READ",
  "IDENTIFICADOR",
  "SYNTAX_ERROR"
  };
}

